### ISSUE TITLE
redis-list-remove! triggers a protocol error

### ISSUE THREAD

**Issue by DarrenN** [Bogdanp/racket-redis#1]
## Background

When calling `redis-list-remove!` the following error is triggered:

```
; Protocol error: expected '$', got ':'
; Context:
;  .../private/client.rkt:137:5
;  .../private/client.rkt:195:9 redis-list-remove!
;  .../private/arrow-higher-order.rkt:379:33
```

## Details

Racket: v7.6 [cs]
OS: macOS Mojave 10.14.6
Redis: stable 6.0.3

## To reproduce

```racket
#lang racket/base

(require redis)

(define client (make-redis))
(define key "foo")

(redis-list-append! client key "a")
(redis-list-remove! client key 0 "a")
```

**Comment by Bogdanp** [comment]
Thanks for the report! The issue was that the count argument wasn't converted to a string before being sent to Redis.
