### ISSUE TITLE
Consider exposing redis-emit! or equivalent

### ISSUE THREAD

**Issue by aymanosman** [Bogdanp/racket-redis#2]
Maybe I've overlooked something, but wouldn't it be nice to expose `redis-emit!` or some such function that just lets you send raw commands to redis?

**Comment by Bogdanp** [comment]
I think I didn't expose it originally because it feels like an implementation detail, but looking at it again, I don't think exposing it would make changing the internals any harder so I'll do it. Out of curiosity, what commands are you missing?

**Comment by Bogdanp** [comment]
The function is now exposed on master.

**Comment by aymanosman** [comment]
Amazing! Thanks for the speedy response.

I found the number of functions exposed bewildering and wanted to follow along with a tutorial with just the straightfoward commands.

Thanks for the library!

**Comment by Bogdanp** [comment]
Happy to help! Let me know if you run into any problems.
