### ISSUE TITLE
Protocol error on symbol hash set

### ISSUE THREAD

**Issue by pmatos** [Bogdanp/racket-redis#3]
Unsure what's happening since I don't have much redis experience but during some experiments I found this:

```
(redis-hash-set! r "bar" `(("type" . "$") ("name" . "€")))
. . Protocol error: expected '$', got ' '
```

Any idea what could be happening here?

**Comment by Bogdanp** [comment]
This looks like a bug with emitting unicode strings. It emits the length in characters, but then sends utf-8 bytes over the wire, which is obviously wrong. I'll push a fix tomorrow. In the mean time, if you use bytes instead of strings, you shouldn't have this issue. This works:

```racket
(redis-hash-set! c "bar" `(("type" . "a") ("name" . ,(string->bytes/utf-8 "€"))))
```

**Comment by pmatos** [comment]
I see - awesome. Thanks for the fix. :)
